export const REG_API_LOADING="REG_API_LOADING"
export const REG_API_SUCCESS="REG_API_SUCCESS"
export const REG_API_FAILURE="REG_API_FAILURE"

export const LOGIN_API_LOADING="LOGIN_API_LOADING"
export const LOGIN_API_SUCCESS="LOGIN_API_SUCCESS"
export const LOGIN_API_FAILURE="LOGIN_API_FAILURE"